# Generated by Django 3.2.13 on 2022-07-19 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CheckItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('speed', models.IntegerField()),
                ('weather', models.CharField(max_length=30)),
                ('surveyor', models.CharField(max_length=30)),
                ('borough', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TimeSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('carrier', models.CharField(max_length=10)),
                ('mph', models.CharField(max_length=10)),
                ('remarks', models.CharField(max_length=100)),
                ('bus', models.IntegerField(verbose_name=10)),
                ('route', models.IntegerField(blank=True, default=None)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='radarSpeedCheck.checkitem')),
            ],
        ),
    ]
