# Generated by Django 3.2.13 on 2022-07-21 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radarSpeedCheck', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='bus',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='mph',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='remarks',
            field=models.SmallIntegerField(choices=[(1, 'Away'), (2, 'Towards'), (3, 'Left Lane'), (4, 'Middle Lane'), (5, 'Right Lane'), (6, 'Northbound')]),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='route',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
