# Generated by Django 3.2.13 on 2022-07-26 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('radarSpeedCheck', '0002_auto_20220721_1552'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checkitem',
            options={'ordering': ['id']},
        ),
    ]
